### ISSUE TITLE
the iOS side doesn't work.

### ISSUE THREAD

**Issue by pheromone** [gameboyVito/react-native-ultimate-listview#10]
你好,我运行你的例子,iOS端不工作,安卓可以工作.报错信息如下:
Hello, I run your example, the iOS side doesn't work, android can work. An error message is as follows:
![11](https://user-images.githubusercontent.com/14305431/27161583-f64339bc-51ae-11e7-9a0f-f8b8f6a13fd7.png)

**Comment by gameboyVito** [comment]
That's an error caused by native-base, try to use native-base@2.1.3 and link the vector-icons again

**Comment by pheromone** [comment]
OK.thank you .

**Comment by gameboyVito** [comment]
@pheromone Hi, I have updated the Example to react-native@0.45.1 and native-base@2.1.5. Just let you know, thanks for reporting this.
