### ISSUE TITLE
iOS上啦刷新问题

### ISSUE THREAD

**Issue by JonsonHI** [gameboyVito/react-native-ultimate-listview#13]
你的代码我改了下,也仔细看了下底层代码
这个问题求教.  也是看了2天了 实在不知道改哪里好.
当数据不满屏的时候.上啦加载更多会不显示end of list
如果数据多的时候,要多啦几次才能显示end  of  list 

updateRows()之后如果没有数据会更新state  (paginationStatus: paginationStatus == 2)
但是这个貌似并没有刷新页面调用最后footer的this.paginationAllLoadedView()方法

所以请帮忙.这地方 有些看不懂了

**Comment by JonsonHI** [comment]
对了 值是IOS 有问题. 安卓是没问题的

**Comment by gameboyVito** [comment]
請問你是用的3.1.4最新版嗎？

**Comment by JonsonHI** [comment]
你的 3.1.4 版本 我iOS跑不起来 例子
Command /bin/sh failed with exit code 1  这个错误
但是我把你的源码拿出来了 放到了我的 例子里

**Comment by gameboyVito** [comment]
EndOfList的這個view是當你的全部數據加載完畢 server返回最新的data是null或者[]的時候才會render的。當數據不足一版時，我這邊使用沒有問題啊。

**Comment by JonsonHI** [comment]
是的我也跟了你的源码  当数据为null的时候
 this.setState({
                isRefreshing: true,
                paginationStatus: paginationStatus
            });

paginationStatus 这个值也都变成2了

但是就是不更新

**Comment by gameboyVito** [comment]
如果數值變了 不更新應該就是render的問題。你是不是在debug模式下測試的？開了remote-debugger不會重新渲染頁面的。試試關了remote並且編個release版看看。

**Comment by JonsonHI** [comment]
release 模式也是一样的.
发现 需要用力向上拉 才会刷新页面 激活this.paginationAllLoadedView()
显示end of list  

但是安卓这边就没有这个问题  
没有数据的时候 会直接显示 end of list

**Comment by gameboyVito** [comment]
你的react-native和react版本是多少？props-> `onEndReachedThreshold` 你有改过吗？

**Comment by JonsonHI** [comment]
},
  "dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-refreshlist": "^1.0.3",
    "react-native-ultimate-listview": "^3.0.2",
    "react-navigation": "^1.0.0-beta.9"
  },
  "devDependencies": {
    "babel-jest": "20.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "20.0.0",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  }

0.44虽然不是最新  但是0.45BUG很多

**Comment by JonsonHI** [comment]
安卓这边我加了一段代码.
在数据不满屏的时候  安卓可以回弹

refreshableScrollView.android 文件
我加了一行代码
else {
                
                    if (y <= height) {
                        this.refs.scrollView.scrollTo({ x: 0, y: height, animated: true });
                    } # **else if(this.props.dataSources.length < 10){
                        this.refs.scrollView.scrollTo({ x: 0, y: height, animated: true });**
                    }else{

                    }
                

            }
onScrollEndDrag 方法里
这样防止安卓这边不满屏数据的时候  没办法回弹.而是超出一个cell距离

**Comment by JonsonHI** [comment]
iOS这边我觉得应该是onScroll 或者是 onScrollEndDrag Y值的问题.
我也修改了一些代码,但是没什么效果.

这个测试下来 偶尔会激活.  大部分还是一直loading

**Comment by gameboyVito** [comment]
pagination跟这个scrollview没有任何关系 这个是当你使用customrefreshview是时候 才会被调用到。所以你改这些y值不会影响pagination到触发 我先看看为什么example跑不了

**Comment by gameboyVito** [comment]
你的`<UltimateListView/>`是怎么用的 发来看看？还有你ios example跑不了 是不是忘记了yarn install？

**Comment by JonsonHI** [comment]
<UltimateListView
                    ref={(ref) => this.listView = ref}
                    key={this.state.layout} //this is important to distinguish different FlatList
                    data={this.state.dataList}
                    onFetch={this.onFetch}
                    keyExtractor={(item, index) => `${index++ + item.id} - ${item}`}  //this is required when you are using FlatList
                    refreshableMode="advanced" //basic or advanced

                    //-------FlatList--------
                    item={this._renderItem}  //this takes two params (item, index)
                    numColumns={this.state.layout === 'list' ? 1 : 3} //to use grid layout, simply set gridColumn > 1
                    columnWrapperStyle={{ height: 120 }}  //use this line to customise style of each row in FlatList, only work when gridColumn > 1

**Comment by JonsonHI** [comment]
<UltimateListView
                    ref={(ref) => this.listView = ref}
                    key={this.state.layout} //this is important to distinguish different FlatList
                    data={this.state.dataList}
                    onFetch={this.onFetch}
                    keyExtractor={(item, index) => `${index++ + item.id} - ${item}`}  //this is required when you are using FlatList
                    refreshableMode="advanced" //basic or advanced

                    //-------FlatList--------
                    item={this._renderItem}  //this takes two params (item, index)
                    numColumns={this.state.layout === 'list' ? 1 : 3} //to use grid layout, simply set gridColumn > 1
                    columnWrapperStyle={{ height: 120 }}  //use this line to customise style of each row in FlatList, only work when gridColumn > 1

**Comment by gameboyVito** [comment]
是不是你没有用 view flex: 1 包起来？
```
<View style={{flex: 1}}>
    <UltimateListView/>
</View>
```

**Comment by JonsonHI** [comment]
<View style={styles.container}>  这个里面有flex : 1

                <UltimateListView


你的例子我用另外一台电脑可以跑起来
但是还是同样问题
上啦时候数据可以加载更多.
问题就出在空数据的时候或者没有数据的时候  就不出发了

**Comment by JonsonHI** [comment]
![gif5](https://user-images.githubusercontent.com/18373125/27904286-d43d0354-626e-11e7-93d7-ef02ef519676.gif)

**Comment by JonsonHI** [comment]
不知道你的是不是这样

**Comment by gameboyVito** [comment]
我例子的确不会触发加载完毕，因为我没有发起服务器的请求，数据是直接本地生成的。我当时的思路应该是 第一次进入 onfetch的时候会发起一次请求 如果rowdata是[] 就直接触发endoflist。其实你这种情况 试试每次pagination的值调大一点 比如一次取20个item 如果server只有10个返回 那么是会正常触发的，如果server有100个，也应该是正常触发的。不触发我觉得是react-native本身的flatlist的`onEndReached`这个callback的问题，他这个的意思是一定要你的flatlist当前屏幕里最下面的那个item靠近屏幕底部才会触发。你gif里面的情况就是这个flatlist的callback根本没有被调用。

**Comment by gameboyVito** [comment]
至于这个触发的距离你可以通过`onEndReachedThreshold`这个props来设置 range是`0 - 1`

**Comment by JonsonHI** [comment]
除了滑动的代码分 iOS和安卓外.其他代码都是一样的
安卓没问题.所以我也不知道到底哪里出现问题了

**Comment by JonsonHI** [comment]
try {
            // //This is required to determinate whether the first loading list is all loaded.
            let pageLimit = 2;
            if (this.state.layout === 'grid') pageLimit = 2;
            let skip = (page - 1) * pageLimit;

            // //Generate dummy data
            let rowData = Array.from({length: pageLimit}, (value, index) => `item -> ${index + skip}`);

            // //Simulate the end of the list if there is no more data returned from the server
            if (page === 3) {
                // this.state.dataList = [];
                rowData = []

            }

            console.log(this.state.dataList);

            //Simulate the network loading in ES7 syntax (async/await)
            await this.sleep(2000);
            startFetch(rowData, pageLimit);
        } catch (err) {
            abortFetch(); //manually stop the refresh or pagination if it encounters network error
            console.log(err);
        }

这是我的onfech 写法.

**Comment by JonsonHI** [comment]
现在问题就是 当数据==null 的时候 并不出发end of list 请求.
所以我认为 和 本地数据 还是 网络数据 并没什么关系

**Comment by gameboyVito** [comment]
安卓和ios的listview原生的代码实现是不一样的。你每次取两个item 根本没有办法触发`onEndReached` 这个触发不来 就不会pagination了。所以要保证个每个page的高度应该大于手机屏幕的高度。默认第一次渲染会触发一次`onEndReached` -> `pagination`, 这也是为什么你只能拿到4个就再也拿不到了。应该就是这个原因。

onEndReached?: ?(info: {distanceFromEnd: number}) => void 
Called once when the scroll position gets within onEndReachedThreshold of the rendered content.

onEndReachedThreshold?: ?number 
How far from the end (in units of visible length of the list) the bottom edge of the list must be from the end of the content to trigger the onEndReached callback. Thus a value of 0.5 will trigger onEndReached when the end of the content is within half the visible length of the list.

**Comment by gameboyVito** [comment]
你如果坚持要每次拿两个 就把那个onEndReachedThreshold设置为0.9

**Comment by JonsonHI** [comment]
不 我在onfech里 只设置了2页  这样是为了方便录屏.
而且上啦触发快的时候  偶尔也能触发到 end of list 
这个是我的 安卓的 GIF

![gif5 4](https://user-images.githubusercontent.com/18373125/27905094-7bf06742-6271-11e7-9a29-5f91dd1640df.gif)

**Comment by gameboyVito** [comment]
我说的不是两页，是每一页里面的item加起来的总高度应该大于当前屏幕高度。

**Comment by gameboyVito** [comment]
```
 try {
        // //This is required to determinate whether the first loading list is all loaded.
        let pageLimit = 10;
        if (this.state.layout === 'grid') pageLimit = 10;
        let skip = (page - 1) * pageLimit;

        // //Generate dummy data
        let rowData = Array.from({length: pageLimit}, (value, index) => `item -> ${index + skip}`);

        // //Simulate the end of the list if there is no more data returned from the server
        if (page === 3) {
            // this.state.dataList = [];
            rowData = []

        }

        console.log(this.state.dataList);

        //Simulate the network loading in ES7 syntax (async/await)
        await this.sleep(2000);
        startFetch(rowData, pageLimit);
    } catch (err) {
        abortFetch(); //manually stop the refresh or pagination if it encounters network error
        console.log(err);
    }
```

**Comment by gameboyVito** [comment]
加上这个onEndReachedThreshold
```
<UltimateListView
                ref={(ref) => this.listView = ref}
                key={this.state.layout} //this is important to distinguish different FlatList
                data={this.state.dataList}
                onFetch={this.onFetch}
                onEndReachedThreshold={0.9}
                keyExtractor={(item, index) => `${index++ + item.id} - ${item}`}  //this is required when you are using FlatList
                refreshableMode="advanced" //basic or advanced

                //-------FlatList--------
                item={this._renderItem}  //this takes two params (item, index)
                numColumns={this.state.layout === 'list' ? 1 : 3} //to use grid layout, simply set gridColumn > 1
                columnWrapperStyle={{ height: 120 }}  //use this line to customise style of each row in FlatList, only work when gridColumn > 1
/>
```

**Comment by JonsonHI** [comment]
加上了也还是一样
其实我看源码 触发这个footer 的代码其实就是paginationStatus = PaginationStatus.allLoaded

然后会调用
   paginationAllLoadedView = () => {
        if (this.props.pagination) {
            if (this.props.paginationAllLoadedView) {
                return this.props.paginationAllLoadedView();
            }

            return (
                <View style={styles.paginationView}>
                    <Text style={{alignSelf: 'center'}}>
                        {this.props.allLoadedText}
                    </Text>
                </View>
            );
        }

        return null;
    };

这样就完成了 end if list 的调用.我总觉得这位置的代码貌似出现问题了

**Comment by JonsonHI** [comment]
![gif5 6](https://user-images.githubusercontent.com/18373125/27905887-fdfbf54c-6273-11e7-86cc-6066d86c8cae.gif)
这是 我的测试

**Comment by JonsonHI** [comment]
知道问题所在了

是sleep 2秒的问题.这2秒内 就不能触发

**Comment by benaheng** [comment]
我也碰到了同样的问题，但并不是 sleep 的原因，pagination调多大也没用

**Comment by gameboyVito** [comment]
我写的sleep的方法是为了模拟网络请求的等待时间，但是本身这个sleep promise可能影响了正常的render 没法触发再次渲染。你可以试试去掉sleep的相关代码 直接给服务器发起请求

**Comment by benaheng** [comment]
去掉了也没用， 这是我的主要代码，你可以测试下看看

`    onFetch = async (page = 1, startFetch, abortFetch) => {
        try {
            let url=`http://news.xtxcm.com/Api/App/app_article_list?num=15&page=${page}&cid=1`
            fetch(url , {
                method: 'GET',
                headers: {},

            }).then((response) => {
                if (response.ok) {
                    return response.json();
                }
            }).then((json) => {


                startFetch(json.data,10)
            }).catch((error) => {
                console.error(error);
            });

        } catch (err) {
            abortFetch();
        }
    };`

` <UltimateListView
            ref={(ref) => this.listView = ref}
            key={this.state.page_name}
            onFetch={this.onFetch}
            keyExtractor={(item, index) => `${item.ap_id}`}
            refreshableMode="advanced" //basic or advanced
            item={this.renderItem}
            numColumns={1}
            columnWrapperStyle={{height: 120}}
            emptyView={this.renderEmptyView}

        />`

**Comment by treemore** [comment]
我也碰到了类似的问题。
感觉是flatlist  的onEndReached  和onRefresh 这两个回调永远也不执行。
外面套view也不行。加高度也不行。。。  这个问题可能跟react-native 版本相关

**Comment by treemore** [comment]
onEndReachedThreshold  这个值在android上面不是百分比。。 ios 不知道。。 facebook上面的文档有可能是错的。。。。   建议试试看onEndReachedThreshold={1000}

**Comment by gameboyVito** [comment]
@JonsonHI @benaheng @treemore Hi, I have fixed this Bug, check the latest version @3.1.6. It is caused by a props called `ListFooterComponent` inside FlatList, this props cannot be triggered re-rendering correctly sometimes. However, the legacy ListView didn't have this issue. To solved this problem, I have to pass a copied dataSource when the end of list is reached. Then the whole list will check if it needs to be re-rendered, so as the `ListFooterComponent`.
