### ISSUE TITLE
a little problem with columnWrapperStyle

### ISSUE THREAD

**Issue by treemore** [gameboyVito/react-native-ultimate-listview#15]
https://github.com/gameboyVito/react-native-ultimate-listview/blob/master/src/ultimateListView.js#L473

maybe  there must be this.props.columnWrapperStyle.

your lib help me mush. thank you

**Comment by gameboyVito** [comment]
Thanks for pointing out, already fixed @3.1.5.

**Comment by treemore** [comment]
i think the flatlist component is not  good for a production . it is more quick than ListView ,but it will more cpu,always let my app can not response touch event . 
so legacyImplementation={true}   is very important

**Comment by gameboyVito** [comment]
You can use the stable version @3.0.2. Thx~

**Comment by treemore** [comment]
<UltimateListView
                    legacyImplementation={true}
                    onFetch={this.onFetch}
                    refreshableMode="advanced"
                    item={this.renderItem}
                    keyExtractor={(item) => ('hot-' + item._id + keySeed++)}
                    numColumn={1}

                />

 "react": "16.0.0-alpha.12",
    "react-native": "0.46.1", //    "react-native": "0.46.2", is not working too.  
"react-native-ultimate-listview": "3.0.2",


the onFetch method i had checked ,no error . the backend return  the right data.

but  the UltimateListView just show loading...  forever .

when i set legacyImplementation={false} ,the same.
when i set refreshableMode="basic" , the same .

**Comment by treemore** [comment]
most time . react-native-ultimate-listview@3.1.5  is working perfect with legacyImplementation={true}. 
except
https://github.com/gameboyVito/react-native-ultimate-listview/blob/master/src/ultimateListView.js#L237
i get a warning .  Cannot read property 'endRefresh' of undefined. maybe is need a check for legacyImplementation. Although it does not seem to affect

**Comment by treemore** [comment]
https://github.com/facebook/react-native/issues/12884
Touch event in the FlatList is delay . let the touch event too slow
