### ISSUE TITLE
似乎没有数据获取出错的情况处理

### ISSUE THREAD

**Issue by LittleLiByte** [gameboyVito/react-native-ultimate-listview#16]
第一次加载数据获取出错一直显示paginationFetchingView，上拉加载数据获取出错一直显示paginationWaitingView，请问可以完善吗 @gameboyVito

**Comment by gameboyVito** [comment]
下拉刷新有一个callback叫做`abortFetch`，你要在你的try catch里面使用。上拉加载更多目前没有处理

**Comment by gameboyVito** [comment]
PR is welcome.
