### ISSUE TITLE
如果只有一条数据的话  waitingSpinnerText这个属性的值会一直显示

### ISSUE THREAD

**Issue by jsshizhan** [gameboyVito/react-native-ultimate-listview#17]
Loading

**Comment by jsshizhan** [comment]
这个字段的值会显示  跟多少条数据没关系，如果数据少的话这个字段的存在就会显得很难看

**Comment by gameboyVito** [comment]
I didn't have this issue, when the initial data is less than your `pageLimit`, then the footer text should be changed to AllLoaded. Make sure your server is returning an empty array [], it's the most important thing to check if all data is loaded.

**Comment by gameboyVito** [comment]
It's all about the pagination and onEndReached, you cannot just hardcode your rowData.

**Comment by jsshizhan** [comment]
谢谢，是我没细看文档

**Comment by iamdurui** [comment]
@jsshizhan @gameboyVito 你怎么处理的啊？我就是按照例子写的，不对啊

onFetch = async (page = 1, startFetch, abortFetch) => {
    try {
      //This is required to determinate whether the first loading list is all loaded.
      let pageLimit = 2;
      let skip = (page - 1) * pageLimit;

      //Generate dummy data
      let rowData = Array.from({length: pageLimit}, (value, index) => `item -> ${index + skip}`);

      //Simulate the end of the list if there is no more data returned from the server
      if (page === 2) {
        rowData = [];
      }

      //Simulate the network loading in ES7 syntax (async/await)
      await this.sleep(2000);
      startFetch(rowData, pageLimit);
    } catch (err) {
      abortFetch(); //manually stop the refresh or pagination if it encounters network error
      console.log(err);
    }
  };
这是我的代码
