### ISSUE TITLE
how to use public method refresh?

### ISSUE THREAD

**Issue by jsshizhan** [gameboyVito/react-native-ultimate-listview#19]
i want to refresh list when navigator goback

**Comment by gameboyVito** [comment]
Simply use ref, like this.refs._listview.refresh()

**Comment by jsshizhan** [comment]
thank you !!

**Comment by himanshuvats1996** [comment]
list is not getting refesh while i am searching an element , but when i pull down then the list shows me the data . 
i used  this.refs._listview.refresh() but not getting updated list after search bar pressed still i have to refresh it
