### ISSUE TITLE
even if there is no data ,roller is also show

### ISSUE THREAD

**Issue by jsshizhan** [gameboyVito/react-native-ultimate-listview#20]
how can i sure height dynamic by data?

**Comment by CoderZF** [comment]
I have same issue !! How to do?

**Comment by gameboyVito** [comment]
Are you using the latest version 3.1.6? What do you mean for roller? The fetchingView or the paginationView?

**Comment by gameboyVito** [comment]
If you mean the ActivityIndicator in the RefreshControl, you need manually call abortFetch() to terminate and stop the refresh animation

**Comment by gameboyVito** [comment]
@CoderZF I guess you may need to implement this props `paginationFetchingView`, and added your own state `error` to determine whether to show a retry button or refreshing spinner.
```
renderPaginationFetchingView = () => {
        if (this.state.error) {
            return (
                <Button />
            );
        }

        return (
            <LoadingSpinner/>
        );
    };
```

**Comment by jsshizhan** [comment]
sorry reply so late, i want to set fetchingView height by myself. i see source you set fetchingView height is Dimensions.get('window').height.can u help me?

**Comment by gameboyVito** [comment]
You should implement your own fetchingView like below:

```
renderPaginationFetchingView = () => {      
    return (
         <LoadingSpinner />
     );
}

<UltimateListView 
    //your other props
    paginationFetchingView={this.renderPaginationFetchingView} />
                 
```

**Comment by jsshizhan** [comment]
i solve the issue by add 
<UltimateListView 
customRefreshViewHeight={-80}/>

i do not know is this the right way

**Comment by jsshizhan** [comment]
`<UltimateListView customRefreshViewHeight={-80}/>`
