### ISSUE TITLE
Android下拉刷新效果

### ISSUE THREAD

**Issue by wuyunqiang** [gameboyVito/react-native-ultimate-listview#22]
博主下拉刷新在数据已经成功加载后 下拉的CustomRefreshView 还是会显示很长时间才会弹回去。
如图 我这里打印可以看到数据已经加载完成了 但是下拉框还是会显示。
希望可以在优化优化。
还有下拉刷新太敏感了 我该怎么调节他的敏感度 现在只要一用力就很容易刷新。

![screenshot_20170821-184727](https://user-images.githubusercontent.com/13480948/29516028-63dce9ce-86a1-11e7-8c4e-a1c917532f47.png)

**Comment by gameboyVito** [comment]
Try the latest version 3.2.0, see if the issue is still remaining.
