### ISSUE TITLE
Android出现闪退情况

### ISSUE THREAD

**Issue by wuyunqiang** [gameboyVito/react-native-ultimate-listview#23]
![screenshot_20170821-165429](https://user-images.githubusercontent.com/13480948/29516143-d3430fdc-86a1-11e7-924b-c06157637dc6.png)
在将全部this.refs.scrollView.scrollTo改成this.refs.scrollView&&this.refs.scrollView.scrollTo后好像没有什么问题了。

**Comment by gameboyVito** [comment]
Should be fixed on v3.2.0
