### ISSUE TITLE
Cannot run example on Android?

### ISSUE THREAD

**Issue by lbhsot** [gameboyVito/react-native-ultimate-listview#24]
Hey guys!

react-native run-android error
Failed to finalize session : -26: Package com.example new target SDK 22 doesn't support runtime permissions but the old target SDK 23 does.

How can i fix it?

**Comment by gameboyVito** [comment]
You may need to open your android studio, follow its pop up alert to fix the compile version inside of gradle setting

**Comment by lbhsot** [comment]
Thank you! It works!
