### ISSUE TITLE
3.0 sectionHeaderView not work?

### ISSUE THREAD

**Issue by Mad-hu** [gameboyVito/react-native-ultimate-listview#4]
sectionHeaderView not work , if i use renderSectionHeader,the refreshView position could not display correctly .
 
![image](https://cloud.githubusercontent.com/assets/13977755/25928200/82a8bbf4-362d-11e7-85f3-20b22b3a7001.png)

**Comment by gameboyVito** [comment]
Hi, have you set legacyImplementation to true because sectionHeader is not supported in FlatList. Turn on this prop to use ListView just like before

**Comment by Mad-hu** [comment]
![image](https://cloud.githubusercontent.com/assets/13977755/25928315/3d7cc3ee-362e-11e7-88dd-1b47e5e6f926.png)

**Comment by Mad-hu** [comment]
in the source code ,i don't see render sectionHeader 

![Uploading QQ20170511-095546.png…]()

**Comment by Mad-hu** [comment]
in the source code ,i don't see render sectionHeader 
![qq20170511-095546](https://cloud.githubusercontent.com/assets/13977755/25928693/33ed72c2-3630-11e7-9631-68418303caca.png)

**Comment by gameboyVito** [comment]
That's because I pass a {...this.props} in the ListView. All props that are supported in ListView will be triggered. If you want to know more props of ListView, you may check the official doc

**Comment by Mad-hu** [comment]
en  but i use renderSectionHeader  ,the first render  ,this refreshview position could not display correctly .

**Comment by gameboyVito** [comment]
Okay I will try it then.

**Comment by Mad-hu** [comment]
don't use 2.* ,first use 3.0,   ios and android  RN0.42 ，problem ios ,android ok , i will send video email gameboyvito@gmail.com

**Comment by Mad-hu** [comment]
@gameboyVito 作者好人，还有两件事：1、  文档上没有 对props withSections 的描述。我还是翻阅你的源码才发现的。希望能够添加到文档上。2 、如何隐藏 上拉加载 ？ 有一些地方不需要上拉  多谢啦！

**Comment by gameboyVito** [comment]
I just pushed the new version yesterday, still working on the doc. About your issue, I actually try and find several quick hacks can help you. 

1. You can use the basic refreshabeMode to use the `sectionHeaderView`
2. If you just want a sticky header always shows on the top of your listView, just put the component on the top of your 
```
<View>
   <Header />
   <UltimateListView />
<View />
```
3. Or, you can set a `<View />` to customise `separator`.

In fact, if you can tell me why you want to use section header and what effect you want to achieve, that would help me to find another solution for you.

**Comment by Mad-hu** [comment]
![qq20170511-134226](https://cloud.githubusercontent.com/assets/13977755/25934328/b3123ca8-364f-11e7-8def-1e2539ca5894.png)
hi! , 我的需求很多，这个是个例子,只能使用sectionHeader来显示月份分组，只是首次进入页面的时候这个refreshView会出现在页面上，下拉一下就会回到正确的位置上了，您能帮助我解决这个问题么

**Comment by Mad-hu** [comment]
如果没有sectionHeader的话  完美运行ios和android 。可是加上sectionHeader，这个refreshView就跑偏了，而且当sectionHeader的高度很大的时候，滚动页面，会出现cellrow悬浮而sectionheader不悬浮的情况，作者好人，帮帮我

**Comment by gameboyVito** [comment]
目前来说，一个快速的解决你的sectionHeader的问题是设置`refreshableMode="basic"`。 另一个问题，上拉隐藏，你需要设置`autoPagination={false}`, 然后`paginationWaitingView={() => <EmptyView />}`.

**Comment by Mad-hu** [comment]
老铁多谢，我非常欣喜能够看到并使用这个项目，已star  期待我的这个问题可以在以后得到解决。为你点赞

**Comment by gameboyVito** [comment]
Thx, I have updated all docs and pushed a new version 3.0.1. The `sectionHeaderView` props I have added to the source code.

**Comment by gameboyVito** [comment]
Hi, @Mad-hu . I have pushed v3.0.2, you can use a new props `pagination={false}` to disable pagination feature.

**Comment by Mad-hu** [comment]
Wow! ,That escalated quickly, it just worked like a charm !! @gameboyVito   🚀
