### ISSUE TITLE
Pull on loading not working

### ISSUE THREAD

**Issue by liuyunqiang** [gameboyVito/react-native-ultimate-listview#5]

**Comment by gameboyVito** [comment]
Please provide some detailed information, like your development environment, your code snippet.....

**Comment by liuyunqiang** [comment]
The old version in the tensile load in android listView without onFetch method  but In the ios works

**Comment by liuyunqiang** [comment]
<UltimateListView
                                               ref= 'listView'
                                               onFetch={this._onListRefersh.bind(this)}
                                               enableEmptySections
                                               headerView={this._renderHeader.bind(this)}
                                               //----Normal Mode----
                                               legacyImplementation={true}
                                               rowView={this._renderRow.bind(this)}
                                               refreshableTitleWillRefresh="下拉刷新..."
                                               refreshableTitleInRefreshing="下拉刷新..."
                                               refreshableTitleDidRefreshDuration={10000}
                                               allLoadedText=''
                                               waitingSpinnerText=''
                                           />
上面是UltimateListView 组件
下面是刷新 加载调用方法
_getCourseList(page, callback, options) {
        var  pageLimit = this.state.pageLimit;
        let that = this;
          InteractionManager.runAfterInteractions(()=>{
             YLYKRnServices.$course.getCourseList({'page':page ,'limit': pageLimit,'album_id': this.props.course_id + '','sorting': this.state.sorting ?'asc' :'desc','category':this.state.filterItem})
              .then((data) => {
                        if (page <= 1) {
                            that._alldata = [];
                        }
                        for (let i = 0; i < data.length; i++) {
                            this._alldata.push(data[i]);
                            this._listened.push(data[i].is_listened);
                        };

                          this.setState({
                              is_listened: this._listened,
                              isLoading:false,
                          });
              YLYKRnStorage.setItem(CACHE_KEY + this.props.course_id + '', this._alldata);
                options.pageLimit = pageLimit;
                callback(data, options);
        }).catch((err) => {
          this.setState({isLoading:false})
          console.warn('load failed: ', err);
        });
      })
    }

    _onListRefersh(page,callback, options) {
      this._getCourseList(page , callback, options);
    }

}

**Comment by gameboyVito** [comment]
I am not sure why you don't want to use `onFetch` method in android. If you do not want to use refresh or pagination feature, why not just implement it by simply using `<View />`.  However, you can try to use `refreshable={false}` to turn off this feature.

**Comment by dongodngtang** [comment]
onEndReached once time,afterward never call onEndReached

**Comment by dongodngtang** [comment]
onEndReached once time,afterward never call onEndReached。why,who tell me ??

**Comment by zhangwen9229** [comment]
把你的关键代码粘出来看看

**Comment by gameboyVito** [comment]
@dongodngtang Have you tried my Example? It seems like the problem is on `onEndReachedThreshold`. In the new `FlatList`, the range of this props is between 0 to 1, but in the older `ListView`, the range varies from 0 to your device height. However, please update your version to `yarn add react-native-ultimate-listview@3.0.2` to see if you still encounter the same problem.

**Comment by gameboyVito** [comment]
@dongodngtang Of course, you may also have wrong use-case on `onFetch()` callback, please provide your code snippet so that I can review it. Thx~

**Comment by dongodngtang** [comment]
componentWillReceiveProps(newProps) {

        const {actionType, raceTickets, loading} = newProps;
        if (actionType === RACE_TICKET
            && loading !== this.props.loading
            && !isEmptyObject(raceTickets)) {

            const {items, last_id} = raceTickets;
            if (last_id != '0')
                this.last_id = last_id;

            if (this.listPage == 1) {
                this.listView.postRefresh(items, 1);
            } else {
                this.listView.postPaginate(items, 1)
            }

            this.setState({
                listTicket: this.listView.getRows()
            })


        }
    }

 onFetch = async(page = 1, startFetch, abortFetch) => {
        try {
            this.listPage = page;
            console.log('listPage:', page)
            if (page === 1) {
                this._onRefresh();
            } else {
                this._onLoadMore();
            }

        } catch (err) {
            abortFetch();
            console.log(err);
        }

    }

**Comment by dongodngtang** [comment]
My react-native 0.43.4
I use Redux to manager data

**Comment by gameboyVito** [comment]
You should not call `postRefresh ` and `postPaginate ` in your own component, these two methods are not public. You can try to remove your whole `componentWillReceiveProps` function, and then modify your `onFetch` method like:
```
onFetch = async(page = 1, startFetch, abortFetch) => {
   try {   
         const rowData = await fetchFromYourAPI('hello');
         const numOfPageItems = 20;
         startFetch(rowData, numOfPageItems);
    } catch (err) {
        abortFetch();
        console.log(err);
    }
}
```

**Comment by denny64** [comment]
@gameboyVito how do i handle pagination? When I fetch the 2nd time, and append that to the end of my array, the listview duplicates the items..? eg. [0....30], then when i fetch again.. result is [0...30, 0...60]
