### ISSUE TITLE
Search by text (FlatList)

### ISSUE THREAD

**Issue by botsbuzz** [gameboyVito/react-native-ultimate-listview#6]
Hey @gameboyVito,
great repository: thank you for your effort on this!

In the Example, when you search for a text you get an error (need a number). My question is: how to search for a text instead of an index?

Any idea?

Thank you again,

Stefano

**Comment by gameboyVito** [comment]
Hi, the search bar in my Example wasn't really for searching content. It is a scrollToIndex showcase. When you input a number(row id), the list will auto-scroll to the item position. If you want to achieve something like content filter, you can reference my code:

```
onChangeFilterText = (filterText) => {
        this.setState({filterText});
        const filterRegex = new RegExp(String(filterText), 'ig');
        const filter = (item) => (
            filterRegex.test(item.name)
        );

        //filter your content by RegEx
        const filteredData = this.state.dataSource.filter(filter);    
        
        //important to update the data source
        this._listView.updateDataSource(filteredData);     
    };
```

**Comment by botsbuzz** [comment]
Awesome! Thank you!
