### ISSUE TITLE
customRefreshView func can't get callback params?

### ISSUE THREAD

**Issue by wuyunqiang** [gameboyVito/react-native-ultimate-listview#9]
I write the customRefreshView and can't get callback params(this.state.refresStatus, this._offsetY)

name of params is wrong.

should be this.state.refreshStatus, this.offsetY... 

is ok

**Comment by gameboyVito** [comment]
@wuyunqiang Hi, I have updated the source, please check out the latest version@3.1.0

**Comment by wuyunqiang** [comment]
OK, this lib is very good.
